### ISSUE TITLE
Display in Fahrenheit?

### ISSUE THREAD

**Issue by adsi4nt** [jeroenpeters1986/piFan#1]
Thank you so much for putting this together and sharing. 

I am playing with this and so far so good! Took me a while to get the on/off to work on my USB port.

I know it is picky, and only used in certain parts of the world, but anyone found a way to have this display and monitor in Fahrenheit instead of Celsius?

**Comment by jeroenpeters1986** [comment]
Hi @adsi4nt, 

as a matter of fact, one of the other uses let me know he did this. I'm gonna contact him to see if he wants so share is code. If not, I will try to do this myself. :-)

I'll let you know!

**Comment by adsi4nt** [comment]
I think I found it... sorry to close my own issue.
https://github.com/adafruit/Adafruit_Python_DHT/blob/master/examples/AdafruitDHT.py

`# Un-comment the line below to convert the temperature to Fahrenheit.
# temperature = temperature * 9/5.0 + 32`

I ran up upgrade and blew everything up so I am starting all over :) I'll report back if this works... trying the base raspbian and building out the touch screen drivers so it might be a few days.

**Comment by jeroenpeters1986** [comment]
Hi @adsi4nt, no problem to close it. Hope you can fix it, take your time and let me know :-)

**Comment by jeroenpeters1986** [comment]
Hi @adsi4nt I just pushed a Fahrenheit branch that you can check out :-)

**Comment by adsi4nt** [comment]
Thanks @jeroenpeters1986 I'll check it out this weekend!
